### ISSUE TITLE
Weird responses that don't make sense

### ISSUE THREAD

**Issue by dennislysenko** [alfianlosari/ChatGPTSwiftUI#17]
<img width="425" alt="image" src="https://github.com/alfianlosari/ChatGPTSwiftUI/assets/5114111/cb3a7d1c-3b57-40ea-baa0-4cdddc89dbeb">

What is going on here?

**Comment by alfianlosari** [comment]
Hi, this is fixed in this commit https://github.com/alfianlosari/ChatGPTSwiftUI/commit/bda026e3c931235a1dbbaf560e5ac7ffd178bc5b
